// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yamore.Services.Database;

#nullable disable

namespace Yamore.Services.Migrations
{
    [DbContext(typeof(_220245Context))]
    [Migration("20251105130537_AddRoleAndUserRole")]
    partial class AddRoleAndUserRole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yamore.Model.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Yamore.Services.Database.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21B76AE4B32B9");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Yamore.Services.Database.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CountryId")
                        .HasName("PK__Countrie__10D1609FFB858505");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Yamore.Services.Database.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12A532B107");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Yamore.Services.Database.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A386A72F213");

                    b.HasIndex("ReservationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Yamore.Services.Database.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YachtId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F244827094F");

                    b.HasIndex("UserId");

                    b.HasIndex("YachtId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Yamore.Services.Database.ReservationService", b =>
                {
                    b.Property<int>("ReservationServicesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationServicesId"));

                    b.Property<int>("ReservationId")
                        .HasColumnType("int")
                        .HasColumnName("ReservationID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.HasKey("ReservationServicesId");

                    b.HasIndex("ReservationId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ReservationServices");
                });

            modelBuilder.Entity("Yamore.Services.Database.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DatePosted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YachtId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CE66E44F78");

                    b.HasIndex("ReservationId");

                    b.HasIndex("UserId");

                    b.HasIndex("YachtId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Yamore.Services.Database.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Yamore.Services.Database.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EndCityId")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedDurationHours")
                        .HasColumnType("int");

                    b.Property<int>("StartCityId")
                        .HasColumnType("int");

                    b.Property<int>("YachtId")
                        .HasColumnType("int");

                    b.HasKey("RouteId")
                        .HasName("PK__Routes__80979B4D3BEC4B3F");

                    b.HasIndex("EndCityId");

                    b.HasIndex("StartCityId");

                    b.HasIndex("YachtId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Yamore.Services.Database.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB00AA4083F57");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Yamore.Services.Database.SpecialRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("RequestId")
                        .HasName("PK__SpecialR__33A8517A69D944E8");

                    b.HasIndex("ReservationId");

                    b.ToTable("SpecialRequests");
                });

            modelBuilder.Entity("Yamore.Services.Database.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C667A3DCC");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534AFDA8DC1")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Yamore.Services.Database.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<DateTime>("DateModification")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Yamore.Services.Database.WeatherForecast", b =>
                {
                    b.Property<int>("ForecastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ForecastId"));

                    b.Property<string>("Condition")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ForecastDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(4, 1)");

                    b.Property<decimal?>("WindSpeed")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ForecastId")
                        .HasName("PK__WeatherF__7F2744781B839532");

                    b.HasIndex("RouteId");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("Yamore.Services.Database.Yacht", b =>
                {
                    b.Property<int>("YachtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("YachtId"));

                    b.Property<int?>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int?>("Cabins")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Length")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("StateMachine")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("YachtId")
                        .HasName("PK__Yachts__0EE60D53D919624E");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Yachts");
                });

            modelBuilder.Entity("Yamore.Services.Database.YachtCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId")
                        .HasName("PK__YachtCat__19093A0B21D26F14");

                    b.ToTable("YachtCategories");
                });

            modelBuilder.Entity("Yamore.Model.UserRole", b =>
                {
                    b.HasOne("Yamore.Services.Database.User", null)
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Yamore.Services.Database.City", b =>
                {
                    b.HasOne("Yamore.Services.Database.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Cities__CountryI__398D8EEE");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Yamore.Services.Database.Notification", b =>
                {
                    b.HasOne("Yamore.Services.Database.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__6754599E");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yamore.Services.Database.Payment", b =>
                {
                    b.HasOne("Yamore.Services.Database.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Reserv__4E88ABD4");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Yamore.Services.Database.Reservation", b =>
                {
                    b.HasOne("Yamore.Services.Database.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__UserI__48CFD27E");

                    b.HasOne("Yamore.Services.Database.Yacht", "Yacht")
                        .WithMany("Reservations")
                        .HasForeignKey("YachtId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__Yacht__49C3F6B7");

                    b.Navigation("User");

                    b.Navigation("Yacht");
                });

            modelBuilder.Entity("Yamore.Services.Database.ReservationService", b =>
                {
                    b.HasOne("Yamore.Services.Database.Reservation", "Reservation")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK_ReservationServices_Reservations");

                    b.HasOne("Yamore.Services.Database.Service", "Service")
                        .WithMany("ReservationServices")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK_ReservationServices_Services");

                    b.Navigation("Reservation");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Yamore.Services.Database.Review", b =>
                {
                    b.HasOne("Yamore.Services.Database.Reservation", "Reservation")
                        .WithMany("Reviews")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__Reserva__59063A47");

                    b.HasOne("Yamore.Services.Database.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__59FA5E80");

                    b.HasOne("Yamore.Services.Database.Yacht", "Yacht")
                        .WithMany("Reviews")
                        .HasForeignKey("YachtId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__YachtId__5AEE82B9");

                    b.Navigation("Reservation");

                    b.Navigation("User");

                    b.Navigation("Yacht");
                });

            modelBuilder.Entity("Yamore.Services.Database.Route", b =>
                {
                    b.HasOne("Yamore.Services.Database.City", "EndCity")
                        .WithMany("RouteEndCities")
                        .HasForeignKey("EndCityId")
                        .IsRequired()
                        .HasConstraintName("FK__Routes__EndCityI__619B8048");

                    b.HasOne("Yamore.Services.Database.City", "StartCity")
                        .WithMany("RouteStartCities")
                        .HasForeignKey("StartCityId")
                        .IsRequired()
                        .HasConstraintName("FK__Routes__StartCit__60A75C0F");

                    b.HasOne("Yamore.Services.Database.Yacht", "Yacht")
                        .WithMany("Routes")
                        .HasForeignKey("YachtId")
                        .IsRequired()
                        .HasConstraintName("FK__Routes__YachtId__5FB337D6");

                    b.Navigation("EndCity");

                    b.Navigation("StartCity");

                    b.Navigation("Yacht");
                });

            modelBuilder.Entity("Yamore.Services.Database.SpecialRequest", b =>
                {
                    b.HasOne("Yamore.Services.Database.Reservation", "Reservation")
                        .WithMany("SpecialRequests")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK__SpecialRe__Reser__6C190EBB");

                    b.Navigation("Reservation");
                });

            modelBuilder.Entity("Yamore.Services.Database.UserRole", b =>
                {
                    b.HasOne("Yamore.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Yamore.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Yamore.Services.Database.WeatherForecast", b =>
                {
                    b.HasOne("Yamore.Services.Database.Route", "Route")
                        .WithMany("WeatherForecasts")
                        .HasForeignKey("RouteId")
                        .IsRequired()
                        .HasConstraintName("FK__WeatherFo__Route__6477ECF3");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Yamore.Services.Database.Yacht", b =>
                {
                    b.HasOne("Yamore.Services.Database.YachtCategory", "Category")
                        .WithMany("Yachts")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Yachts__Category__44FF419A");

                    b.HasOne("Yamore.Services.Database.City", "Location")
                        .WithMany("Yachts")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK__Yachts__Location__440B1D61");

                    b.HasOne("Yamore.Services.Database.User", "Owner")
                        .WithMany("Yachts")
                        .HasForeignKey("OwnerId")
                        .IsRequired()
                        .HasConstraintName("FK__Yachts__OwnerId__4316F928");

                    b.Navigation("Category");

                    b.Navigation("Location");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Yamore.Services.Database.City", b =>
                {
                    b.Navigation("RouteEndCities");

                    b.Navigation("RouteStartCities");

                    b.Navigation("Yachts");
                });

            modelBuilder.Entity("Yamore.Services.Database.Country", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("Yamore.Services.Database.Reservation", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("ReservationServices");

                    b.Navigation("Reviews");

                    b.Navigation("SpecialRequests");
                });

            modelBuilder.Entity("Yamore.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Yamore.Services.Database.Route", b =>
                {
                    b.Navigation("WeatherForecasts");
                });

            modelBuilder.Entity("Yamore.Services.Database.Service", b =>
                {
                    b.Navigation("ReservationServices");
                });

            modelBuilder.Entity("Yamore.Services.Database.User", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("UserRoles");

                    b.Navigation("Yachts");
                });

            modelBuilder.Entity("Yamore.Services.Database.Yacht", b =>
                {
                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Yamore.Services.Database.YachtCategory", b =>
                {
                    b.Navigation("Yachts");
                });
#pragma warning restore 612, 618
        }
    }
}
